kind: Pod
apiVersion: v1
metadata:
  name: labelsandselector
  labels:                     #labels
    env: development          #key-value pair
    class: pods               #can have multiple labels
spec:
  containers:
    - name: con01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo label pod; sleep 5; done"]