kind: Deployment
apiVerion: apps/v1
metadata:
  name: mydeployment                      # This will be deployment name
spec:
  replicas: 2
  selector:
    matchLabels:
      deplymentEnv: stage
    template:
      metadata:
        name: testpod
        labels:
          deploymentEnv: stage
      spec:
        containers:
          - name: con01
            image: ubuntu
            commands: [""] 